default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: neverends_development

test:
  <<: *default
  database: neverends_test

production:
  <<: *default
  port: 5432
  database: myapp
  user: deploy
  password: deploy
